- name: Get device information
  hosts: all
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - set_fact:
      tmp_dir: "tmp"

  - set_fact:
      conf_file: "{{ tmp_dir}}/{{ inventory_hostname }}.conf"

  - name: creating a directory
    file:
         path: "{{ tmp_dir }}"
         state: directory

  - name: save device config
    template:
         src: config_template.j2
         dest: "{{ conf_file }}"

#  - name: Load configuration data using strings and commit
#    junos_install_config:
#        host: "{{ ansible_host}}"
#        username: regress
#        password: MaRtInI
#        port: 22
#        format: "set"
#        file: "{{ conf_file }}"
#        timeout: 120
#    register: junos_result

    - name: Execute commands on a Juniper Device to get info (current)...
      juniper_junos_config:
        retrieve: committed
        check: false
        commit: false
        format: text
        options:
          inherit: "inherit"
        provider:
          host: "{{device_management_ip}}"
          username: "{{device_username}}"
          password: "{{device_password}}"
          port: 22
      register: command_resp_current
      ignore_errors: true
